<?php
$images = array(
  array('ID' => '68','Title' => 'Sand','Year' => '2023','Filters' => 'black purple','Link' => 'Sand.png'),
  array('ID' => '67','Title' => 'Star Chariot','Year' => '2023','Filters' => 'multi black gray','Link' => 'Star\\ Chariot.png'),
  array('ID' => '66','Title' => 'This Is the Coolest Dude You Have Ever Seen','Year' => '2023','Filters' => 'blue multi','Link' => 'This\\ Is\\ the\\ Coolest\\ Dude\\ You\\ Have\\ Ever\\ Seen.png'),
  array('ID' => '65','Title' => 'Lumian, Midnight Sun','Year' => '2023','Filters' => 'thin gold white black multi','Link' => 'Lumian,\\ Midnight\\ Sun.png'),
  array('ID' => '64','Title' => 'Forever','Year' => '2023','Filters' => 'orange red purple','Link' => 'Forever.png'),
  array('ID' => '63','Title' => 'The Keeper','Year' => '2023','Filters' => 'green','Link' => 'The\\ Keeper.png'),
  array('ID' => '62','Title' => 'Blue Men','Year' => '2023','Filters' => 'blue white','Link' => 'Blue\\ Men.png'),
  array('ID' => '61','Title' => 'Cloud Pass','Year' => '2023','Filters' => 'gold orange white','Link' => 'Cloud\\ Pass.png'),
  array('ID' => '60','Title' => 'Moonlight Tower','Year' => '2023','Filters' => 'black blue','Link' => 'Moonlight\\ Tower.png'),
  array('ID' => '59','Title' => 'There is a Guy','Year' => '2023','Filters' => 'black blue','Link' => 'There\\ is\\ a\\ Guy.png'),
  array('ID' => '58','Title' => 'Shinefish','Year' => '2023','Filters' => 'black blue multi','Link' => 'Shinefish.png'),
  array('ID' => '57','Title' => 'Draconic Dawn','Year' => '2023','Filters' => 'gray gold','Link' => 'Draconic\\ Dawn.png'),
  array('ID' => '56','Title' => 'Life Is Good when there Is a Bunny','Year' => '2023','Filters' => 'black blue','Link' => 'Star\\ Bunny.png'),
  array('ID' => '55','Title' => 'Lumian, Light that Eclipses the Stars','Year' => '2023','Filters' => 'gold blue','Link' => 'Lumian,\\ Light\\ that\\ Eclipses\\ the\\ Stars.png'),
  array('ID' => '54','Title' => 'Black Daylight','Year' => '2023','Filters' => 'black blue','Link' => 'Black\\ Daylight.png'),
  array('ID' => '53','Title' => 'The Announcer','Year' => '2023','Filters' => 'black thin','Link' => 'The\\ Announcer.png'),
  array('ID' => '52','Title' => 'King Wyrm','Year' => '2023','Filters' => 'red blue white','Link' => 'King\\ Wyrm.png'),
  array('ID' => '51','Title' => 'Moon Chariot','Year' => '2023','Filters' => 'blue white black multi','Link' => 'Moon\\ Chariot.png'),
  array('ID' => '50','Title' => 'Toxic','Year' => '2023','Filters' => 'purple gold black multi','Link' => 'Toxic-\\ Landscape\\ Alt.png'),
  array('ID' => '49','Title' => 'Lumian, Wings of Light','Year' => '2023','Filters' => 'blue gold multi','Link' => 'Lumian,\\ Wings\\ of\\ Light.png'),
  array('ID' => '48','Title' => 'What if Someone Told You There Is Another Way','Year' => '2023','Filters' => 'blue multi thin','Link' => 'What\\ if\\ Someone\\ Told\\ You\\ There\\ Is\\ Another\\ Way.png'),
  array('ID' => '47','Title' => 'Hold them Closer','Year' => '2023','Filters' => 'red black mono','Link' => 'Hold\\ them\\ Closer.png'),
  array('ID' => '46','Title' => 'Bartender Bun','Year' => '2023','Filters' => 'multi white blue thin','Link' => 'Bartender\\ Bun.png'),
  array('ID' => '45','Title' => 'Astral Buluc','Year' => '2023','Filters' => 'black purple mono thin','Link' => 'Astral\\ Buluc.png'),
  array('ID' => '44','Title' => 'Rudolph, the Red Nosed, Reigns Here','Year' => '2022','Filters' => 'black blue red multi','Link' => 'Rudolph,\\ the\\ Red\\ Nosed,\\ Reigns\\ Here.png'),
  array('ID' => '43','Title' => 'Nobody is Coming to Help','Year' => '2022','Filters' => 'white orange','Link' => 'Nobody\\ is\\ Coming\\ to\\ Help.png'),
  array('ID' => '42','Title' => 'Take a Step, Take a Breath','Year' => '2022','Filters' => 'multi black red','Link' => 'Take\\ a\\ Step,\\ Take\\ a\\ Breath.png'),
  array('ID' => '41','Title' => 'Dining with the Darkness','Year' => '2022','Filters' => 'multi black green gold','Link' => 'Dining\\ with\\ the\\ Darkness.png'),
  array('ID' => '40','Title' => 'Voice of Destiny','Year' => '2022','Filters' => 'red purple gold thin','Link' => 'Voice\\ of\\ Destiny.png'),
  array('ID' => '39','Title' => 'Horns of the Ascended','Year' => '2022','Filters' => 'white gold gray','Link' => 'Horns\\ of\\ the\\ Ascended.png'),
  array('ID' => '38','Title' => 'Banishment','Year' => '2022','Filters' => 'blue gray mono','Link' => 'Banishment.png'),
  array('ID' => '37','Title' => 'Lumian, Shrine of Light','Year' => '2022','Filters' => 'blue purple gold multi','Link' => 'Lumian,\\ Shrine\\ of\\ Light.png'),
  array('ID' => '36','Title' => 'When to Go','Year' => '2022','Filters' => 'purple black blue mono','Link' => 'When\\ to\\ Go.png'),
  array('ID' => '35','Title' => 'Sommerkatze','Year' => '2022','Filters' => 'gold orange thin','Link' => 'Sommerkatze.png'),
  array('ID' => '34','Title' => 'A Billion Stars to Singular Purpose','Year' => '2022','Filters' => 'blue purple','Link' => 'A\\ Billion\\ Stars\\ to\\ Singular\\ Purpose.png'),
  array('ID' => '33','Title' => 'Here the Heart','Year' => '2022','Filters' => 'black white purple mono','Link' => 'Here\\ the\\ Heart.png'),
  array('ID' => '32','Title' => 'Seeker Strike','Year' => '2022','Filters' => 'black purple mono thin','Link' => 'Seeker\\ Strike.png'),
  array('ID' => '31','Title' => 'Seeker Statues','Year' => '2022','Filters' => 'white purple','Link' => 'Seeker\\ Statues.png'),
  array('ID' => '30','Title' => 'Sweet Release','Year' => '2022','Filters' => 'gray green red multi thin','Link' => 'Sweet\\ Release.png'),
  array('ID' => '29','Title' => 'Legion','Year' => '2022','Filters' => 'gray green multi','Link' => 'Legion.png'),
  array('ID' => '28','Title' => 'Stellar Mesa Valley','Year' => '2022','Filters' => 'black purple blue mono thin','Link' => 'Stellar\\ Mesa\\ Valley.png'),
  array('ID' => '27','Title' => 'Mystic Frog','Year' => '2022','Filters' => 'purple mono','Link' => 'Mystic\\ Frog.png'),
  array('ID' => '26','Title' => 'Island of Light','Year' => '2022','Filters' => 'purple mono','Link' => 'Island\\ of\\ Light.png'),
  array('ID' => '25','Title' => 'Kings\' Might','Year' => '2022','Filters' => 'gold black mono thin','Link' => 'Kings\\ Might.png'),
  array('ID' => '24','Title' => 'Stormstar','Year' => '2022','Filters' => 'blue gray black mono thin','Link' => 'Stormstar.png'),
  array('ID' => '23','Title' => 'Lucas the Vengeful','Year' => '2022','Filters' => 'blue orange black multi thin','Link' => 'Lucas\\ the\\ Vengeful.png'),
  array('ID' => '22','Title' => 'Lucas, the Dark Blue','Year' => '2022','Filters' => 'blue orange black multi thin','Link' => 'Lucas,\\ the\\ Dark\\ Blue.png'),
  array('ID' => '21','Title' => 'SUPREME BUG!!!','Year' => '2022','Filters' => 'blue gold multi','Link' => 'SUPREME\\ BUG!!!.png'),
  array('ID' => '20','Title' => 'Dust Duo','Year' => '2022','Filters' => 'red multi','Link' => 'Dust\\ Duo.png'),
  array('ID' => '19','Title' => 'Funny Image of Frog in Mug','Year' => '2022','Filters' => 'purple white green multi thin','Link' => 'Funny\\ Image\\ of\\ Frog\\ in\\ Mug.png'),
  array('ID' => '18','Title' => 'Portal Hub','Year' => '2022','Filters' => 'black multi','Link' => 'Portal\\ Hub.png'),
  array('ID' => '17','Title' => 'Lumian, Blade of Light','Year' => '2021','Filters' => 'blue multi','Link' => 'Lumian,\\ Blade\\ of\\ Light.png'),
  array('ID' => '16','Title' => 'Doti','Year' => '2021','Filters' => 'red white multi','Link' => 'Doti.png'),
  array('ID' => '15','Title' => 'Astral Conclusion','Year' => '2021','Filters' => 'blue purple black','Link' => 'Astral\\ Conclusion.png'),
  array('ID' => '14','Title' => 'Galactic Wish','Year' => '2021','Filters' => 'blue orange black','Link' => 'Galactic\\ Wish.png'),
  array('ID' => '13','Title' => 'King of the Untold','Year' => '2021','Filters' => 'purple gold red','Link' => 'King\\ of\\ the\\ Untold.png'),
  array('ID' => '12','Title' => 'Prince of the Untold','Year' => '2021','Filters' => 'purple gold black','Link' => 'Prince\\ of\\ the\\ Untold.png'),
  array('ID' => '11','Title' => 'The Untold','Year' => '2021','Filters' => 'purple gold','Link' => 'The\\ Untold.png'),
  array('ID' => '10','Title' => 'Marsh Mamma','Year' => '2020','Filters' => 'green thin','Link' => 'Marsh\\ Mamma.png'),
  array('ID' => '9','Title' => 'You Left Your Egg','Year' => '2020','Filters' => 'gold orange','Link' => 'You\\ Left\\ Your\\ Egg.png'),
  array('ID' => '8','Title' => 'Elemancer\'s Wyvern','Year' => '2020','Filters' => 'blue gray multi thin','Link' => 'Elemancers\\ Wyvern.png'),
  array('ID' => '7','Title' => 'Dream Express','Year' => '2020','Filters' => 'white purple multi','Link' => 'Dream\\ Express.png'),
  array('ID' => '6','Title' => 'Welcome the Infinite','Year' => '2020','Filters' => 'purple','Link' => 'Welcome\\ the\\ Infinite.png'),
  array('ID' => '5','Title' => 'Shrimpclaw Leviathan','Year' => '2020','Filters' => 'black blue','Link' => 'Shrimpclaw\\ Leviathan.png'),
  array('ID' => '4','Title' => 'World Seven Final Boss','Year' => '2020','Filters' => 'red black orange','Link' => 'World\\ Seven\\ Final\\ Boss.png'),
  array('ID' => '3','Title' => 'Monstrosity of the void','Year' => '2020','Filters' => 'black gray mono','Link' => 'Monstrosity\\ of\\ the\\ Void.png'),
  array('ID' => '2','Title' => 'Dawn of Spring','Year' => '2020','Filters' => 'green mono','Link' => 'Dawn\\ of\\ Spring.png'),
  array('ID' => '1','Title' => 'Drake of Worlds','Year' => '2020','Filters' => 'white red mono','Link' => 'Drake\\ of\\ Worlds.png'),
  array('ID' => '0','Title' => 'Draconic Dusk','Year' => '2020','Filters' => 'purple','Link' => 'Draconic\\ Dusk.png'),
  );
?>
